[package]
name = "distributedfilesystem"
version = "0.1.0"
authors = ["0x0mini <jamalbore@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.9"